# Site settings
title: "Jekyll Bootstrap RTL Theme"
author: Your Name
email: your@mail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
description: "Your site description"
copyright: "Commons Attribution 4.0 International"
robot: ""
keywords: "Jekyll Hebrew Bootstrap Jekyll-theme"
encoding: utf-8
twitter_username: user
github_username:  user
fullname: "user name"
favicon: "assets/img/favicon.png"

permalink: :title.html

timezone: Israel/Jerusalem

paginate: 5
paginate_path: "/page:num/"

tag_page_layout: tag_page
tag_page_dir: tag

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

lang: he_IL

disqus: false
disqus_shortname:

google_analytics_id:

debate: false
debate_acc:

widgetpack: false
widgetpack_id:
